#!/usr/bin/env node
/**
 * Generate apps/web/public/sitemap.xml.
 *
 * lastmod comes from each source file's last git commit date, so the sitemap
 * stays honest without anyone remembering to touch it. Answer engines weight
 * freshness heavily and a stale hand-maintained lastmod is worse than none —
 * it claims an update that did not happen.
 *
 * Output is written back into public/ (not dist/) so the generated file is
 * reviewable in version control and vite copies it on the next build.
 *
 * Run: node scripts/generate-sitemap.mjs
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync, statSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://www.timer.simple-tech.app';
const OUT = resolve(ROOT, 'apps/web/public/sitemap.xml');

/**
 * Every indexable URL, with the source file its lastmod is derived from.
 *
 * Deliberately absent:
 *  - /app and /oauth/redirect — the SPA shell has no static content of its own
 *    and canonicalises to the home page.
 *  - /404.html — noindex.
 *  - /zoom/* — the Zoom app is noindex.
 */
const PAGES = [
  { path: '/', file: 'apps/web/index.html', priority: '1.0', changefreq: 'weekly' },

  // Content / SEO pages
  { path: '/toastmasters-timer-role-guide', file: 'apps/web/public/toastmasters-timer-role-guide.html', priority: '0.8', changefreq: 'monthly' },
  { path: '/toastmasters-speech-types-and-timing', file: 'apps/web/public/toastmasters-speech-types-and-timing.html', priority: '0.8', changefreq: 'monthly' },
  { path: '/toastmasters-timing-chart', file: 'apps/web/public/toastmasters-timing-chart.html', priority: '0.8', changefreq: 'monthly' },
  { path: '/toastmasters-timer-script', file: 'apps/web/public/toastmasters-timer-script.html', priority: '0.8', changefreq: 'monthly' },
  { path: '/table-topics-timer', file: 'apps/web/public/table-topics-timer.html', priority: '0.8', changefreq: 'monthly' },
  { path: '/toastmasters-speech-contest-timing-rules', file: 'apps/web/public/toastmasters-speech-contest-timing-rules.html', priority: '0.8', changefreq: 'yearly' },
  { path: '/how-to-use-zoom-for-toastmasters', file: 'apps/web/public/how-to-use-zoom-for-toastmasters.html', priority: '0.8', changefreq: 'monthly' },
  { path: '/toastmasters-zoom-timer-backgrounds', file: 'apps/web/public/toastmasters-zoom-timer-backgrounds.html', priority: '0.8', changefreq: 'monthly' },
  { path: '/best-toastmasters-timer-apps', file: 'apps/web/public/best-toastmasters-timer-apps.html', priority: '0.8', changefreq: 'monthly' },

  // Video pages
  { path: '/toastmasters-timer-demo', file: 'apps/web/public/toastmasters-timer-demo.html', priority: '0.6', changefreq: 'monthly' },
  { path: '/toastmasters-timer-zoom-demo', file: 'apps/web/public/toastmasters-timer-zoom-demo.html', priority: '0.6', changefreq: 'monthly' },

  // Legal / support (served from the zoom app's public dir at the root path)
  { path: '/documentation', file: 'apps/zoom-app/public/documentation.html', priority: '0.5', changefreq: 'monthly' },
  { path: '/support', file: 'apps/zoom-app/public/support.html', priority: '0.3', changefreq: 'yearly' },
  { path: '/privacy', file: 'apps/zoom-app/public/privacy.html', priority: '0.3', changefreq: 'yearly' },
  { path: '/terms-of-use', file: 'apps/zoom-app/public/terms-of-use.html', priority: '0.3', changefreq: 'yearly' },
];

/** Last git commit date for a file (YYYY-MM-DD), or null if unavailable. */
function gitLastModified(relPath) {
  try {
    const out = execFileSync(
      'git',
      ['log', '-1', '--format=%cs', '--', relPath],
      { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }
    ).trim();
    return /^\d{4}-\d{2}-\d{2}$/.test(out) ? out : null;
  } catch {
    return null;
  }
}

/** Filesystem mtime as YYYY-MM-DD. Used for files git has not seen yet. */
function fileMtime(relPath) {
  const abs = resolve(ROOT, relPath);
  if (!existsSync(abs)) return null;
  return statSync(abs).mtime.toISOString().slice(0, 10);
}

const missing = [];
const entries = PAGES.map((page) => {
  if (!existsSync(resolve(ROOT, page.file))) missing.push(page.file);
  // Prefer the commit date; fall back to mtime for uncommitted new pages.
  const lastmod = gitLastModified(page.file) || fileMtime(page.file) || null;
  return { ...page, lastmod };
});

if (missing.length) {
  console.error('generate-sitemap: source file(s) not found:\n  ' + missing.join('\n  '));
  process.exit(1);
}

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...entries.map((e) =>
    [
      '  <url>',
      `    <loc>${ORIGIN}${e.path}</loc>`,
      e.lastmod ? `    <lastmod>${e.lastmod}</lastmod>` : null,
      `    <changefreq>${e.changefreq}</changefreq>`,
      `    <priority>${e.priority}</priority>`,
      '  </url>',
    ]
      .filter(Boolean)
      .join('\n')
  ),
  '</urlset>',
  '',
].join('\n');

writeFileSync(OUT, xml, 'utf8');
console.log(`generate-sitemap: wrote ${entries.length} URLs to ${OUT.replace(ROOT + '/', '')}`);
